var R=require("../../../../chunks/ssr/[turbopack]_runtime.js")("server/app/admin/(panel)/gallery/page.js")
R.c("server/chunks/ssr/[root-of-the-server]__0bk38x8._.js")
R.c("server/chunks/ssr/1hdb_next_dist_1qi4b0u._.js")
R.c("server/chunks/ssr/1hdb_next_dist_esm_build_templates_app-page_060ll0s.js")
R.c("server/chunks/ssr/[root-of-the-server]__1u36muo._.js")
R.c("server/chunks/ssr/[root-of-the-server]__1-szdpm._.js")
R.c("server/chunks/ssr/[root-of-the-server]__1mk3p8q._.js")
R.c("server/chunks/ssr/1hdb_next_dist_client_components_1hb0vvq._.js")
R.c("server/chunks/ssr/1hdb_next_dist_client_components_builtin_forbidden_0h00pax.js")
R.c("server/chunks/ssr/1hdb_next_dist_client_components_builtin_unauthorized_0wmhxa-.js")
R.c("server/chunks/ssr/1hdb_next_dist_client_components_builtin_global-error_0_j2o50.js")
R.c("server/chunks/ssr/src_017en5u._.js")
R.c("server/chunks/ssr/_next-internal_server_app_admin_(panel)_gallery_page_actions_1d-h65t.js")
R.m(66401)
module.exports=R.m(66401).exports
