var R=require("../../chunks/ssr/[turbopack]_runtime.js")("server/app/mice/page.js")
R.c("server/chunks/ssr/[root-of-the-server]__05f2zlr._.js")
R.c("server/chunks/ssr/_03wtiv4._.js")
R.c("server/chunks/ssr/1hdb_next_dist_esm_build_templates_app-page_0jp5pc9.js")
R.c("server/chunks/ssr/1hdb_next_dist_1qi4b0u._.js")
R.c("server/chunks/ssr/_0n3owwq._.js")
R.c("server/chunks/ssr/[root-of-the-server]__1u36muo._.js")
R.c("server/chunks/ssr/[root-of-the-server]__1-szdpm._.js")
R.c("server/chunks/ssr/[root-of-the-server]__1mk3p8q._.js")
R.c("server/chunks/ssr/1hdb_next_dist_client_components_1hb0vvq._.js")
R.c("server/chunks/ssr/1hdb_next_dist_client_components_builtin_forbidden_0h00pax.js")
R.c("server/chunks/ssr/1hdb_next_dist_client_components_builtin_unauthorized_0wmhxa-.js")
R.c("server/chunks/ssr/1hdb_next_dist_client_components_builtin_global-error_0_j2o50.js")
R.c("server/chunks/ssr/_next-internal_server_app_mice_page_actions_1lgn33w.js")
R.m(28431)
module.exports=R.m(28431).exports
