var R=require("../../../../../chunks/[turbopack]_runtime.js")("server/app/api/bookings/[id]/send-brochure/route.js")
R.c("server/chunks/[root-of-the-server]__0vqlkl6._.js")
R.c("server/chunks/[root-of-the-server]__086j-ie._.js")
R.c("server/chunks/1hdb_next_dist_esm_build_templates_app-route_192pllu.js")
R.c("server/chunks/1hdb_next_09f355t._.js")
R.c("server/chunks/[root-of-the-server]__05djxk5._.js")
R.c("server/chunks/src_lib_db_ts_12rrbm4._.js")
R.c("server/chunks/1hdb_next_09idqcn._.js")
R.c("server/chunks/[root-of-the-server]__0_rhs0r._.js")
R.c("server/chunks/_next-internal_server_app_api_bookings_[id]_send-brochure_route_actions_11p5nub.js")
R.m(62272)
module.exports=R.m(62272).exports
