var R=require("../../../../../../chunks/[turbopack]_runtime.js")("server/app/api/agent/bookings/[id]/documents/route.js")
R.c("server/chunks/[root-of-the-server]__167301-._.js")
R.c("server/chunks/1hdb_next_09f355t._.js")
R.c("server/chunks/[root-of-the-server]__086j-ie._.js")
R.c("server/chunks/src_lib_db_ts_12rrbm4._.js")
R.c("server/chunks/1hdb_next_09idqcn._.js")
R.c("server/chunks/[root-of-the-server]__0_rhs0r._.js")
R.c("server/chunks/1oeh_server_app_api_agent_bookings_[id]_documents_route_actions_0mocuv7.js")
R.m(72635)
module.exports=R.m(72635).exports
