var R=require("../../../../chunks/[turbopack]_runtime.js")("server/app/api/agent/bookings/route.js")
R.c("server/chunks/[root-of-the-server]__086j-ie._.js")
R.c("server/chunks/1hdb_next_09f355t._.js")
R.c("server/chunks/[root-of-the-server]__1851j6g._.js")
R.c("server/chunks/src_lib_db_ts_12rrbm4._.js")
R.c("server/chunks/1hdb_next_09idqcn._.js")
R.c("server/chunks/[root-of-the-server]__0_rhs0r._.js")
R.c("server/chunks/_next-internal_server_app_api_agent_bookings_route_actions_0sgjazu.js")
R.m(68286)
module.exports=R.m(68286).exports
