// This file is generated automatically by Next.js
// Do not edit this file manually

type AppRoutes = "/" | "/about" | "/account" | "/account/bookings/[id]" | "/account/bookings/[id]/quotation" | "/admin" | "/admin/agents" | "/admin/blog" | "/admin/bookings" | "/admin/bookings/[id]" | "/admin/bookings/new" | "/admin/customers" | "/admin/departures" | "/admin/destinations" | "/admin/enquiries" | "/admin/features" | "/admin/gallery" | "/admin/login" | "/admin/packages" | "/admin/testimonials" | "/agent" | "/agent/bookings/[id]" | "/agent/bookings/new" | "/agent/login" | "/blog" | "/blog/[slug]" | "/book" | "/contact" | "/destinations" | "/destinations/[id]" | "/mice" | "/packages" | "/packages/[id]" | "/plan-trip" | "/signin" | "/signup" | "/testimonials"
type AppRouteHandlerRoutes = "/api/admin/agents" | "/api/admin/agents/[id]" | "/api/admin/bookings" | "/api/admin/customers" | "/api/admin/customers/[id]" | "/api/admin/departures" | "/api/admin/departures/[id]" | "/api/admin/login" | "/api/admin/logout" | "/api/agent/bookings" | "/api/agent/bookings/[id]" | "/api/agent/bookings/[id]/documents" | "/api/agent/bookings/[id]/notify" | "/api/agent/login" | "/api/agent/logout" | "/api/auth/login" | "/api/auth/logout" | "/api/auth/me" | "/api/auth/signup" | "/api/bookings" | "/api/bookings/[id]" | "/api/bookings/[id]/brochure" | "/api/bookings/[id]/confirmation" | "/api/bookings/[id]/send-brochure" | "/api/bookings/mine" | "/api/departures" | "/api/email-preview/booking-confirmation" | "/api/email-preview/custom-package" | "/api/email-preview/quotation-brochure" | "/api/uploadthing"
type PageRoutes = never
type LayoutRoutes = "/" | "/admin" | "/agent"
type RedirectRoutes = never
type RewriteRoutes = never
type Routes = AppRoutes | PageRoutes | LayoutRoutes | RedirectRoutes | RewriteRoutes | AppRouteHandlerRoutes


interface ParamMap {
  "/": {}
  "/about": {}
  "/account": {}
  "/account/bookings/[id]": { "id": string; }
  "/account/bookings/[id]/quotation": { "id": string; }
  "/admin": {}
  "/admin/agents": {}
  "/admin/blog": {}
  "/admin/bookings": {}
  "/admin/bookings/[id]": { "id": string; }
  "/admin/bookings/new": {}
  "/admin/customers": {}
  "/admin/departures": {}
  "/admin/destinations": {}
  "/admin/enquiries": {}
  "/admin/features": {}
  "/admin/gallery": {}
  "/admin/login": {}
  "/admin/packages": {}
  "/admin/testimonials": {}
  "/agent": {}
  "/agent/bookings/[id]": { "id": string; }
  "/agent/bookings/new": {}
  "/agent/login": {}
  "/api/admin/agents": {}
  "/api/admin/agents/[id]": { "id": string; }
  "/api/admin/bookings": {}
  "/api/admin/customers": {}
  "/api/admin/customers/[id]": { "id": string; }
  "/api/admin/departures": {}
  "/api/admin/departures/[id]": { "id": string; }
  "/api/admin/login": {}
  "/api/admin/logout": {}
  "/api/agent/bookings": {}
  "/api/agent/bookings/[id]": { "id": string; }
  "/api/agent/bookings/[id]/documents": { "id": string; }
  "/api/agent/bookings/[id]/notify": { "id": string; }
  "/api/agent/login": {}
  "/api/agent/logout": {}
  "/api/auth/login": {}
  "/api/auth/logout": {}
  "/api/auth/me": {}
  "/api/auth/signup": {}
  "/api/bookings": {}
  "/api/bookings/[id]": { "id": string; }
  "/api/bookings/[id]/brochure": { "id": string; }
  "/api/bookings/[id]/confirmation": { "id": string; }
  "/api/bookings/[id]/send-brochure": { "id": string; }
  "/api/bookings/mine": {}
  "/api/departures": {}
  "/api/email-preview/booking-confirmation": {}
  "/api/email-preview/custom-package": {}
  "/api/email-preview/quotation-brochure": {}
  "/api/uploadthing": {}
  "/blog": {}
  "/blog/[slug]": { "slug": string; }
  "/book": {}
  "/contact": {}
  "/destinations": {}
  "/destinations/[id]": { "id": string; }
  "/mice": {}
  "/packages": {}
  "/packages/[id]": { "id": string; }
  "/plan-trip": {}
  "/signin": {}
  "/signup": {}
  "/testimonials": {}
}


export type ParamsOf<Route extends Routes> = ParamMap[Route]

interface LayoutSlotMap {
  "/": never
  "/admin": never
  "/agent": never
}


export type { AppRoutes, PageRoutes, LayoutRoutes, RedirectRoutes, RewriteRoutes, ParamMap, AppRouteHandlerRoutes }

declare global {
  /**
   * Props for Next.js App Router page components
   * @example
   * ```tsx
   * export default function Page(props: PageProps<'/blog/[slug]'>) {
   *   const { slug } = await props.params
   *   return <div>Blog post: {slug}</div>
   * }
   * ```
   */
  interface PageProps<AppRoute extends AppRoutes> {
    params: Promise<ParamMap[AppRoute]>
    searchParams: Promise<Record<string, string | string[] | undefined>>
  }

  /**
   * Props for Next.js App Router layout components
   * @example
   * ```tsx
   * export default function Layout(props: LayoutProps<'/dashboard'>) {
   *   return <div>{props.children}</div>
   * }
   * ```
   */
  type LayoutProps<LayoutRoute extends LayoutRoutes> = {
    params: Promise<ParamMap[LayoutRoute]>
    children: React.ReactNode
  } & {
    [K in LayoutSlotMap[LayoutRoute]]: React.ReactNode
  }

  /**
   * Context for Next.js App Router route handlers
   * @example
   * ```tsx
   * export async function GET(request: NextRequest, context: RouteContext<'/api/users/[id]'>) {
   *   const { id } = await context.params
   *   return Response.json({ id })
   * }
   * ```
   */
  interface RouteContext<AppRouteHandlerRoute extends AppRouteHandlerRoutes> {
    params: Promise<ParamMap[AppRouteHandlerRoute]>
  }
}
