// This file is generated automatically by Next.js
// Do not edit this file manually
// This file validates that all pages and layouts export the correct types

import type { AppRoutes, LayoutRoutes, ParamMap, AppRouteHandlerRoutes } from "./routes.js"
import type { ResolvingMetadata, ResolvingViewport } from "next/types.js"
import type { NextRequest } from 'next/server.js'

type AppPageConfig<Route extends AppRoutes = AppRoutes> = {
  default: React.ComponentType<{ params: Promise<ParamMap[Route]> } & any> | ((props: { params: Promise<ParamMap[Route]> } & any) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type LayoutConfig<Route extends LayoutRoutes = LayoutRoutes> = {
  default: React.ComponentType<LayoutProps<Route>> | ((props: LayoutProps<Route>) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type RouteHandlerConfig<Route extends AppRouteHandlerRoutes = AppRouteHandlerRoutes> = {
  GET?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  POST?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PUT?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PATCH?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  DELETE?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  HEAD?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  OPTIONS?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
}


// Validate ../../src/app/about/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/about">> = Specific
  const handler = {} as typeof import("../../src/app/about/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/account/bookings/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/account/bookings/[id]">> = Specific
  const handler = {} as typeof import("../../src/app/account/bookings/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/account/bookings/[id]/quotation/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/account/bookings/[id]/quotation">> = Specific
  const handler = {} as typeof import("../../src/app/account/bookings/[id]/quotation/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/account/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/account">> = Specific
  const handler = {} as typeof import("../../src/app/account/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/admin/(panel)/agents/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/agents">> = Specific
  const handler = {} as typeof import("../../src/app/admin/(panel)/agents/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/admin/(panel)/blog/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/blog">> = Specific
  const handler = {} as typeof import("../../src/app/admin/(panel)/blog/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/admin/(panel)/bookings/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/bookings/[id]">> = Specific
  const handler = {} as typeof import("../../src/app/admin/(panel)/bookings/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/admin/(panel)/bookings/new/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/bookings/new">> = Specific
  const handler = {} as typeof import("../../src/app/admin/(panel)/bookings/new/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/admin/(panel)/bookings/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/bookings">> = Specific
  const handler = {} as typeof import("../../src/app/admin/(panel)/bookings/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/admin/(panel)/customers/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/customers">> = Specific
  const handler = {} as typeof import("../../src/app/admin/(panel)/customers/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/admin/(panel)/departures/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/departures">> = Specific
  const handler = {} as typeof import("../../src/app/admin/(panel)/departures/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/admin/(panel)/destinations/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/destinations">> = Specific
  const handler = {} as typeof import("../../src/app/admin/(panel)/destinations/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/admin/(panel)/enquiries/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/enquiries">> = Specific
  const handler = {} as typeof import("../../src/app/admin/(panel)/enquiries/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/admin/(panel)/features/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/features">> = Specific
  const handler = {} as typeof import("../../src/app/admin/(panel)/features/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/admin/(panel)/gallery/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/gallery">> = Specific
  const handler = {} as typeof import("../../src/app/admin/(panel)/gallery/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/admin/(panel)/packages/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/packages">> = Specific
  const handler = {} as typeof import("../../src/app/admin/(panel)/packages/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/admin/(panel)/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin">> = Specific
  const handler = {} as typeof import("../../src/app/admin/(panel)/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/admin/(panel)/testimonials/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/testimonials">> = Specific
  const handler = {} as typeof import("../../src/app/admin/(panel)/testimonials/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/admin/login/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/login">> = Specific
  const handler = {} as typeof import("../../src/app/admin/login/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/agent/(panel)/bookings/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/agent/bookings/[id]">> = Specific
  const handler = {} as typeof import("../../src/app/agent/(panel)/bookings/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/agent/(panel)/bookings/new/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/agent/bookings/new">> = Specific
  const handler = {} as typeof import("../../src/app/agent/(panel)/bookings/new/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/agent/(panel)/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/agent">> = Specific
  const handler = {} as typeof import("../../src/app/agent/(panel)/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/agent/login/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/agent/login">> = Specific
  const handler = {} as typeof import("../../src/app/agent/login/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/blog/[slug]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/blog/[slug]">> = Specific
  const handler = {} as typeof import("../../src/app/blog/[slug]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/blog/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/blog">> = Specific
  const handler = {} as typeof import("../../src/app/blog/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/book/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/book">> = Specific
  const handler = {} as typeof import("../../src/app/book/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/contact/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/contact">> = Specific
  const handler = {} as typeof import("../../src/app/contact/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/destinations/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/destinations/[id]">> = Specific
  const handler = {} as typeof import("../../src/app/destinations/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/destinations/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/destinations">> = Specific
  const handler = {} as typeof import("../../src/app/destinations/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/mice/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/mice">> = Specific
  const handler = {} as typeof import("../../src/app/mice/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/packages/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/packages/[id]">> = Specific
  const handler = {} as typeof import("../../src/app/packages/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/packages/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/packages">> = Specific
  const handler = {} as typeof import("../../src/app/packages/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/">> = Specific
  const handler = {} as typeof import("../../src/app/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/plan-trip/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/plan-trip">> = Specific
  const handler = {} as typeof import("../../src/app/plan-trip/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/signin/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/signin">> = Specific
  const handler = {} as typeof import("../../src/app/signin/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/signup/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/signup">> = Specific
  const handler = {} as typeof import("../../src/app/signup/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/testimonials/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/testimonials">> = Specific
  const handler = {} as typeof import("../../src/app/testimonials/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/admin/agents/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/agents/[id]">> = Specific
  const handler = {} as typeof import("../../src/app/api/admin/agents/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/admin/agents/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/agents">> = Specific
  const handler = {} as typeof import("../../src/app/api/admin/agents/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/admin/bookings/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/bookings">> = Specific
  const handler = {} as typeof import("../../src/app/api/admin/bookings/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/admin/customers/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/customers/[id]">> = Specific
  const handler = {} as typeof import("../../src/app/api/admin/customers/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/admin/customers/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/customers">> = Specific
  const handler = {} as typeof import("../../src/app/api/admin/customers/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/admin/departures/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/departures/[id]">> = Specific
  const handler = {} as typeof import("../../src/app/api/admin/departures/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/admin/departures/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/departures">> = Specific
  const handler = {} as typeof import("../../src/app/api/admin/departures/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/admin/login/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/login">> = Specific
  const handler = {} as typeof import("../../src/app/api/admin/login/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/admin/logout/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/logout">> = Specific
  const handler = {} as typeof import("../../src/app/api/admin/logout/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/agent/bookings/[id]/documents/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/agent/bookings/[id]/documents">> = Specific
  const handler = {} as typeof import("../../src/app/api/agent/bookings/[id]/documents/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/agent/bookings/[id]/notify/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/agent/bookings/[id]/notify">> = Specific
  const handler = {} as typeof import("../../src/app/api/agent/bookings/[id]/notify/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/agent/bookings/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/agent/bookings/[id]">> = Specific
  const handler = {} as typeof import("../../src/app/api/agent/bookings/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/agent/bookings/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/agent/bookings">> = Specific
  const handler = {} as typeof import("../../src/app/api/agent/bookings/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/agent/login/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/agent/login">> = Specific
  const handler = {} as typeof import("../../src/app/api/agent/login/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/agent/logout/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/agent/logout">> = Specific
  const handler = {} as typeof import("../../src/app/api/agent/logout/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/auth/login/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/auth/login">> = Specific
  const handler = {} as typeof import("../../src/app/api/auth/login/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/auth/logout/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/auth/logout">> = Specific
  const handler = {} as typeof import("../../src/app/api/auth/logout/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/auth/me/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/auth/me">> = Specific
  const handler = {} as typeof import("../../src/app/api/auth/me/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/auth/signup/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/auth/signup">> = Specific
  const handler = {} as typeof import("../../src/app/api/auth/signup/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/bookings/[id]/brochure/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/bookings/[id]/brochure">> = Specific
  const handler = {} as typeof import("../../src/app/api/bookings/[id]/brochure/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/bookings/[id]/confirmation/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/bookings/[id]/confirmation">> = Specific
  const handler = {} as typeof import("../../src/app/api/bookings/[id]/confirmation/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/bookings/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/bookings/[id]">> = Specific
  const handler = {} as typeof import("../../src/app/api/bookings/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/bookings/[id]/send-brochure/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/bookings/[id]/send-brochure">> = Specific
  const handler = {} as typeof import("../../src/app/api/bookings/[id]/send-brochure/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/bookings/mine/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/bookings/mine">> = Specific
  const handler = {} as typeof import("../../src/app/api/bookings/mine/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/bookings/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/bookings">> = Specific
  const handler = {} as typeof import("../../src/app/api/bookings/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/departures/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/departures">> = Specific
  const handler = {} as typeof import("../../src/app/api/departures/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/email-preview/booking-confirmation/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/email-preview/booking-confirmation">> = Specific
  const handler = {} as typeof import("../../src/app/api/email-preview/booking-confirmation/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/email-preview/custom-package/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/email-preview/custom-package">> = Specific
  const handler = {} as typeof import("../../src/app/api/email-preview/custom-package/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/email-preview/quotation-brochure/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/email-preview/quotation-brochure">> = Specific
  const handler = {} as typeof import("../../src/app/api/email-preview/quotation-brochure/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/uploadthing/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/uploadthing">> = Specific
  const handler = {} as typeof import("../../src/app/api/uploadthing/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}





// Validate ../../src/app/admin/(panel)/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/admin">> = Specific
  const handler = {} as typeof import("../../src/app/admin/(panel)/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/agent/(panel)/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/agent">> = Specific
  const handler = {} as typeof import("../../src/app/agent/(panel)/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/">> = Specific
  const handler = {} as typeof import("../../src/app/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}
